### ISSUE TITLE
Fragment transaction breaks layout if exitUntilCollapsed flag is set

### ISSUE THREAD

**Issue by mikhailmelnik** [material-components/material-components-android#1019]
**Description:**
The pretty much standard layout of
```
CoordinatorLayout
    AppBarLayout
        CollapsingToolbarLayout [app:layout_scrollFlags="scroll|snap|exitUntilCollapsed"]
            Toolbar
NestedScrollView [app:layout_behavior="@string/appbar_scrolling_view_behavior"]
```
in fragment works pretty well until fragment transaction happens (e.g. switch to another fragment and come back). 

With no `exitUntilCollapsed` flag set original fragment got restored as it should keeping the scroll position etc. But if this flag is set various issues happen after the fragment transaction including scroll position reset (sometimes) and (pretty much always) inability to move scrolled content (including overscroll effect) to the view port.

Removal of `exitUntilCollapsed` flag makes the whole thing work again but at the price of Toolbar visibility.

**Source code:**
https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/tableofcontents/res/layout/cat_toc_fragment.xml

**Android API version:**
23

**Material Library version:** 
master branch

**Device:**
LG G3

**Demo:**
After I've switched to another fragment and came back the part of content ("Transitions" label, overscroll etc) became unavailable:

![example](https://user-images.githubusercontent.com/3161857/74525037-4de6e680-4f74-11ea-8259-47b86f6b3aa7.gif)

**Comment by lvcmenezes** [comment]
Same problem here, did you manage to find a fix for it?

**Comment by mikhailmelnik** [comment]
@lvcmenezes nope, and I wonder how does world live with that without any complain.

**Comment by mikhailmelnik** [comment]
@lvcmenezes looks like I found a workaround, not sure though if it works in all circumstances:

```
override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
    val view = ...
    view.postDelayed(0) { view.requestLayout() }
    return view
}
```

**Comment by mikhailmelnik** [comment]
@chrisbanes could be this issue related the issue you've fixed with https://github.com/material-components/material-components-android/pull/299 ?

**Comment by mariuspena** [comment]
I have almost the same issue. I have tried version 1.1.0, and 1.2.0-alpha06

See video: 
https://youtu.be/Q_LaMnwhOyU

1. 1st view: a Fragment that has CoordinatorLayout, it scrolls fine. 
2. go to another activity (same setup.. ) 
2.1. if I do not touch any view in the activity and go back, the fragment scrolls fine
2.2. if I focus on an EditText, or click on a Button and then go back > the header scrolls, the content stays in the same place. 

PS: since the 1st view (the fragment) is part of a Navigation (with NavHostFragment and BottomNavigationView) ... sometimes the other fragments have 0 width and height (so a blank page.. although the api calls work, recyclers are populated, etc)

**Comment by mikhailmelnik** [comment]
Fixed by https://github.com/material-components/material-components-android/commit/a21a30026a33fc20cf7ad699d32d1298b84096c6

**Comment by crocsandcoffee** [comment]
I don't believe this issue has been fixed yet. I am using the below layout: 
```
<CoordinatorLayout

    <RecyclerView app:layout_behavior="@string/appbar_scrolling_view_behavior"
    
    <AppBarLayout
     
        <CollapsingToolbarLayout app:layout_scrollFlags="scroll|exitUntilCollapsed"
    
```

and let's say the toolbar is in collapsed state, and user has scrolled somewhere in the list, taps a list item and navigates to another fragment. Hitting back, the fragment transaction is replaced, and the toolbar is in expanded state but scroll pos in recycler view hasn't changed. it almost looks like the Collapsing toolbar expands as the fragment is existing, so when returning to it, it's not expanded. 

I tested with version `1.3.0-rc01` which was tagged above as having a commit that fixes this issue.

**Comment by OhhhThatVarun** [comment]
Yes, it is not fixed. I tested it with `1.13.0-alpha02`. I'm having the same issue as @crocsandcoffee. The `CollapsingToolbarLayout` just doesn't stay collapsed.

**Comment by BanDroid** [comment]
also not fixed for me, i have a video for it.

<details>
  <summary>mylayout.xml</summary>
  <pre><code><?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="false"
    tools:context=".activity.anime.fragment.detail.Fragment">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/fragment_detail_appbar"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/fragment_detail_collapsing_toolbar"
            style="?attr/collapsingToolbarLayoutLargeStyle"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:expandedTitleTextColor="@android:color/transparent">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="true"
                app:layout_collapseMode="pin">

                <ImageView
                    android:id="@+id/fragment_detail_thumbnail"
                    android:layout_width="match_parent"
                    android:layout_height="250dp"
                    android:scaleType="centerCrop"
                    android:background="?attr/colorSurfaceContainer"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent" />

                <LinearLayout
                    android:id="@+id/fragment_detail_cover_container"
                    android:layout_width="180dp"
                    android:layout_height="280dp"
                    android:padding="8dp"
                    android:layout_marginTop="?attr/collapsingToolbarLayoutMediumSize"
                    android:layout_marginBottom="16dp"
                    android:background="?attr/colorSurfaceContainerHighest"
                    android:layout_gravity="center_horizontal"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent">

                    <ImageView
                        android:id="@+id/fragment_detail_cover"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:scaleType="centerCrop" />

                </LinearLayout>

                <com.google.android.material.textview.MaterialTextView
                    android:id="@+id/fragment_detail_title"
                    style="?attr/textAppearanceHeadlineMedium"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:paddingTop="@dimen/inner_spacing"
                    android:paddingHorizontal="@dimen/inner_spacing"
                    android:textAlignment="center"
                    android:textStyle="bold"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@id/fragment_detail_cover_container"
                    tools:text="Title" />

                <com.google.android.material.textview.MaterialTextView
                    android:id="@+id/fragment_detail_alternative_title"
                    style="?attr/textAppearanceHeadlineSmall"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:paddingHorizontal="@dimen/inner_spacing"
                    tools:text="Alternative Title"
                    android:textAlignment="center"
                    android:alpha="0.7"
                    app:layout_constraintTop_toBottomOf="@id/fragment_detail_title"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent" />
            </androidx.constraintlayout.widget.ConstraintLayout>

            <com.google.android.material.appbar.MaterialToolbar
                android:id="@+id/fragment_detail_toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:title="@string/detail_fragment_label"
                app:navigationIcon="@drawable/baseline_arrow_back_24"
                app:navigationIconTint="?attr/colorControlNormal"
                app:layout_collapseMode="pin" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>
    </com.google.android.material.appbar.AppBarLayout>

    <androidx.core.widget.NestedScrollView
        android:id="@+id/fragment_detail_nested_scroll"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fillViewport="true"
        android:fitsSystemWindows="false"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingHorizontal="@dimen/inner_spacing"
            android:paddingTop="8dp"
            android:paddingBottom="?attr/actionBarSize"
            android:fitsSystemWindows="false">

            <androidx.core.widget.ContentLoadingProgressBar
                android:id="@+id/fragment_detail_progressbar"
                style="?android:attr/progressBarStyle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="@dimen/inner_spacing"
                android:indeterminate="true"
                android:layout_gravity="center"
                android:visibility="visible"
                tools:visibility="gone"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent" />

            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/fragment_detail_content"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:visibility="gone"
                tools:visibility="visible"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintBottom_toBottomOf="parent">

                <com.google.android.material.textview.MaterialTextView
                    android:id="@+id/fragment_detail_synopsis_title"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="?attr/textAppearanceTitleMedium"
                    android:text="@string/common_synopsis"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent" />

                <com.google.android.material.textview.MaterialTextView
                    android:id="@+id/fragment_detail_synopsis_body"
                    style="?attr/textAppearanceBodyMedium"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:paddingVertical="@dimen/inner_spacing"
                    android:alpha="0.7"
                    android:textIsSelectable="true"
                    tools:text="@string/lorem_ipsum"
                    app:layout_constraintTop_toBottomOf="@id/fragment_detail_synopsis_title"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent" />

                <LinearLayout
                    android:id="@+id/fragment_detail_ads_banner_1"
                    android:layout_width="0dp"
                    android:layout_height="60dp"
                    android:orientation="vertical"
                    android:gravity="center_horizontal|center_vertical"
                    app:layout_constraintTop_toBottomOf="@id/fragment_detail_synopsis_body"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent" />

                <com.google.android.material.textview.MaterialTextView
                    android:id="@+id/fragment_detail_additional_info_title"
                    style="?attr/textAppearanceTitleMedium"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginVertical="@dimen/inner_spacing"
                    android:text="@string/common_additional_info"
                    app:layout_constraintTop_toBottomOf="@id/fragment_detail_ads_banner_1"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent" />

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/inner_spacing"
                    android:paddingBottom="@dimen/inner_spacing"
                    android:orientation="vertical"
                    android:divider="@drawable/divider_space"
                    android:showDividers="middle"
                    app:layout_constraintTop_toBottomOf="@id/fragment_detail_additional_info_title"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent">

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_status"
                        tools:text="Status" />

                    <TextView
                        android:id="@+id/fragment_detail_status"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelMedium"
                        tools:text="Completed" />

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_studio"
                        tools:text="Status" />

                    <com.google.android.material.chip.ChipGroup
                        android:id="@+id/fragment_detail_studios"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:singleLine="false"
                        app:chipSpacingHorizontal="8dp"
                        app:chipSpacingVertical="4dp" />

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_release"
                        tools:text="Status" />

                    <TextView
                        android:id="@+id/fragment_detail_release"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelMedium"
                        tools:text="Jul 25, 2025" />

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_season"
                        tools:text="Status" />

                    <TextView
                        android:id="@+id/fragment_detail_season"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelMedium"
                        android:textColor="?attr/colorPrimary"
                        tools:text="Summer 2025" />

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_type"
                        tools:text="Tipe" />

                    <TextView
                        android:id="@+id/fragment_detail_type"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelMedium"
                        tools:text="OVA" />

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_censor"
                        tools:text="Sensor" />

                    <TextView
                        android:id="@+id/fragment_detail_censor"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelMedium"
                        tools:text="Uncensored" />

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_added"
                        tools:text="Ditambahkan" />

                    <TextView
                        android:id="@+id/fragment_detail_created"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelMedium"
                        tools:text="Agustus 9, 2025" />

                    
                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelLarge"
                        android:text="@string/common_updated_on"
                        tools:text="Diperbarui" />

                    <TextView
                        android:id="@+id/fragment_detail_updated"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        style="@style/TextAppearance.KaitoAni.LabelMedium"
                        tools:text="Agustus 9, 2025" />

                    <com.google.android.material.chip.ChipGroup
                        android:id="@+id/fragment_detail_genres"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:singleLine="false"
                        app:chipSpacingHorizontal="8dp"
                        app:chipSpacingVertical="4dp" />
                </LinearLayout>

            </androidx.constraintlayout.widget.ConstraintLayout>

            <org.kaitoani.widget.SystemBarSpacer
                android:layout_width="match_parent"
                android:layout_height="0dp"
                app:layout_constraintTop_toBottomOf="@id/fragment_detail_content" />

        </androidx.constraintlayout.widget.ConstraintLayout>

    </androidx.core.widget.NestedScrollView>

    <com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/fragment_detail_menu"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:hideOnScroll="true"
        app:layout_behavior="com.google.android.material.bottomappbar.BottomAppBar$Behavior"
        app:menu="@menu/menu_detail" />

    <com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton
        android:id="@+id/fragment_detail_show_episodes"
        style="@style/Widget.Material3.ExtendedFloatingActionButton.Primary"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/common_watch"
        app:layout_anchor="@id/fragment_detail_menu"
        app:icon="@drawable/baseline_playlist_play_24" />

</androidx.coordinatorlayout.widget.CoordinatorLayout></code></pre>
</details>

> NSFW WARNING!!!

<details>
  <summary>Video demonstration:</summary>
  <video src="https://github.com/user-attachments/assets/1625b947-b3d5-4cbd-ae0f-cd116821dacc"></video>
</details>
