### ISSUE TITLE
[Snackbar] Setting LayoutParams for SnackbarLayout doesn't work

### ISSUE THREAD

**Issue by Zoro38** [material-components/material-components-android#1076]
**Description:**

There is no effect when trying to set LayoutParams for the SnackbarLayout (i.e. adding some margins).
I tried to add margins to the Snackbar because I wanted it not to stick to the bottom edges of the screen. Instead, I wanted it to float just like shown in the Material design guidelines.

This bug does not occur on Library version 1.0.0. I've reproduced this issue with version 1.1.0 and also with the latest alpha (1.2.0-alpha05).

**Expected behavior:**

![expected](https://user-images.githubusercontent.com/18499748/75632463-9224e880-5bfc-11ea-9122-1f3a61f06167.png)

**Actual behavior:**

![actual](https://user-images.githubusercontent.com/18499748/75632466-97823300-5bfc-11ea-8f1d-84ae7469911a.png)

**Source code:** 

```
Snackbar snackbar = Snackbar.make(getView(), "Test", Snackbar.LENGTH_LONG);
Snackbar.SnackbarLayout snackbarLayout = (Snackbar.SnackbarLayout) snackbar.getView();
CoordinatorLayout.LayoutParams layoutParams = (CoordinatorLayout.LayoutParams) 
snackbarLayout.getLayoutParams();
layoutParams.setMargins(32, 0, 32, 32);
snackbarLayout.setLayoutParams(layoutParams);
snackbar.show();
```

**Android API version:** 29

**Material Library version:** 1.1.0 and 1.2.0-alpha05

**Device:** Samsung Galaxy S10 and Android Emulator (Pixel 2 API 29)

**Comment by jairrab** [comment]
Can confirm this issue. The last version where the margin behavior was working properly was with version 1.1.0-alpha10.  After that, the margin is not working.

**Comment by KirillBorodin** [comment]
Guys, I am just faced this issue right before release the app to Google Play. Fortunately before, and not after...

**Comment by ankushyerawar** [comment]
Facing same issue could anyone help!!

**Comment by danielgomezrico** [comment]
I believe you are using the wrong style to setup the Snackbar, you need to use this in the app theme:
> <item name="snackbarStyle">@style/Widget.MaterialComponents.Snackbar</item>

Instead of `@style/Widget.MaterialComponents.Snackbar.FullWidth`.

**Comment by dpreussler** [comment]
it seems there is a general issue here, setting margins dont seem to work via xml.

None of these work:

```
    <style name="MySnackbar" parent="@style/Widget.MaterialComponents.Snackbar">
        <item name="android:layout_marginLeft">50dp</item>
        <item name="android:layout_marginRight">50dp</item>
        <item name="android:layout_marginBottom">100dp</item>
    </style>
```
especially the bottom one is very unfortunate. Just moving up the Snackbar is sth we are doing via code (which also doenst work anymore)

Reason and the only one that works seems:
```
        <item name="android:layout_margin">100dp</item>
```
but this will then mess up side margins too.

**Comment by ricknout** [comment]
Here is a way to achieve this using styles (for example, just a custom bottom margin):
```
<style name="Theme.App" parent="Theme.MaterialComponents.Light.NoActionBar">
    ...
    <item name="snackbarStyle">@style/Widget.App.Snackbar</item>
</style>

<style name="Widget.App.Snackbar" parent="Widget.MaterialComponents.Snackbar">
    <item name="android:layout_margin">@null</item>
    <!-- Use default Snackbar margins for top/left/right -->
    <item name="android:layout_marginTop">@dimen/mtrl_snackbar_margin</item>
    <item name="android:layout_marginLeft">@dimen/mtrl_snackbar_margin</item>
    <item name="android:layout_marginRight">@dimen/mtrl_snackbar_margin</item>
    <!-- Custom bottom margin, this could work for top/left/right too -->
    <item name="android:layout_marginBottom">100dp</item>
</style>
```

**Comment by Glaurock** [comment]
Last post solution seems to work thanks. 
But "snackbarStyle" will apply for every SnackBar in app.
What if we need to have different snackbars with different margin?

**Comment by danielgomezrico** [comment]
Im not happy with setting `@null`, how can you know that it will work fine in all devices?

**Comment by sylviestephanies** [comment]
is there any update on this?

**Comment by ssawchenko** [comment]
Also experiencing this issue. Any update?

**Comment by ankushyerawar** [comment]
@sylviestephanies @ssawchenko 
I resolver this issue just by adding this
     `<style name="Theme.App" parent="Theme.MaterialComponents.Light.NoActionBar">` 

before i was using this
     `<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">`

**Comment by cchencool** [comment]
I temporally solved this problem by code below. Reflact field `originalMargins` in `BaseTransientBottomBar`, and set the bottom margin into this field. When it call `BaseTransientBottomBar#updateMargins()`, the real layout will be updated. It works fine on both 1.1.0 & 1.2.0 release version.
```
    private boolean fixSnackBarMarginBottomBug(Object snackBar, int height) {
        try {
            Class snackbarClass = Class.forName("com.google.android.material.snackbar.Snackbar");
            Field originalMarginsField = snackbarClass.getSuperclass().getDeclaredField("originalMargins");
            originalMarginsField.setAccessible(true);
            Rect fixedOriginalMargins = new Rect();
            fixedOriginalMargins.bottom = height;
            originalMarginsField.set(snackBar, fixedOriginalMargins);
            return true;
        } catch (IllegalAccessException | NoSuchFieldException | ClassNotFoundException e) {
            LogUtils.d(TAG, "fixSnackBarMarginBottomBug error.");
        }
        return false;
    }
```

**Comment by bhavindhodia** [comment]
Adding CoordinatorLayout or Frame Layout and then setting margin didn't work for me 

To tackle this problem use Drawable Background where use item to set Margin and shape to set desired Padding

**container_snackbar.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <!--    Set Margin Here -->
    <item
        android:left="20dp"
        android:right="20dp"
        android:bottom="10dp"
        android:top="10dp">

        <!-- Insert your shape here: -->
        <shape android:shape="rectangle"  >
            <solid android:color="#FE4C4C" />

            <!-- Padding for inner text-->
            <padding android:left="25dp" android:right="10dp" android:bottom="10dp" android:top="10dp" />
            <corners android:radius="5dp" />

        </shape>
    </item>
</layer-list>
```

And then from Activity  set that Drawable

**MainActivity.java**
```
Snackbar snack = Snackbar
                 .make(activity,"Hello World 🚀",Snackbar.LENGTH_INDEFINITE);
        snack.getView()
        .setBackground(ContextCompat.getDrawable(getApplicationContext(),R.drawable.contianer_snackbar));
        snack.show();
```


[Result][1]
 
  [1]: https://i.stack.imgur.com/uTh7k.png

**Comment by iMrTidy** [comment]
I confirm this issue in the version 1.3.0.1 while 1.0.0.1 still works fine. Workarounds above either does not make it or not possible in my project. Please fix this.

**Comment by atulgpt** [comment]
Is there any update on this?

**Comment by drchen** [comment]
It looks like the issue has been fixed. Can you provide more info if it's still somehow reproducible?

**Comment by atulgpt** [comment]
Hi @drchen right now I have fixed my library version at an older version due to this issue as this Github issue say that issue is still open. So I didn't try this with the newer version. I will try and update. Meanwhile, if this issue is fixed can you close this bug?

**Comment by atulgpt** [comment]
Hi, @drchen I tried with `1.5.0` and the issue is still reproducing. Are you sure you looked at the right place? It's sad that it's been around two years and the issue is still reproducing and no one is tracking it :(

**Comment by drchen** [comment]
I'll take a second look. 

In the meantime it will be nice if you can provide your code sample which reproduces the issue. : )

**Comment by 1hakr** [comment]
if anyone is looking for a workaround with the latest version, this updated method should work.

```
    public static boolean fixSnackBarMarginBottom(Snackbar snackBar, int height) {
        try {
            Field marginsField = Snackbar.class.getSuperclass().getDeclaredField("extraBottomMarginWindowInset");
            marginsField.setAccessible(true);
            marginsField.set(snackBar, height);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
```

**Comment by drchen** [comment]
The issue should be fixed in 1.6.0 alpha03 already. Please let me know if this is still happening. : )

**Comment by Mihir3646** [comment]
Getting the error while using the SnackbarLayout - after updating the lib version from 1.9.0 to 1.10.0

Current lib version`com.google.android.material:material:1.10.0`

> SnackbarLayout can only be accessed from within the same library group (referenced groupId=com.google.android.material

**Comment by shakiz** [comment]
> Getting the error while using the SnackbarLayout - after updating the lib version from 1.9.0 to 1.10.0
> 
> Current lib version`com.google.android.material:material:1.10.0`
> 
> > SnackbarLayout can only be accessed from within the same library group (referenced groupId=com.google.android.material

Any luck with this one?
