### ISSUE TITLE
TextInputLayout hint text not vertically center

### ISSUE THREAD

**Issue by houdangui1985** [material-components/material-components-android#120]
Our design team follow the   iOS catalog app , the hint text of TextInputLayout is vertically center, but when I try Android it is not.  I don't seem to find an option to make it.  So they are different ?  Or there's some way to make it?

**Comment by afohrman** [comment]
Thanks for bringing this up. You are correct that the label should be vertically centered. I have a PR I'm working on now to vertically center the label text. It should land in the next week or so on GitHub.

**Comment by Dwite** [comment]
@afohrman Hello, just curious how is your PR going?

**Comment by FlorianVidal66** [comment]
Hello @afohrman, any news about the fix ?

**Comment by afohrman** [comment]
Sure. It turns out that fixing this bug properly requires a refactor of TextInputLayout's box draw. It's likely that this refactor won't be necessary once shapes theming is introduced to text fields, so I'm holding off on doing the refactor for now. The plan is to use MaterialShapeDrawable for the background and move away from using the EditText's underline, which is the source of the issue.

**Comment by FlorianVidal66** [comment]
Thanks for the quick answer @afohrman  👍

**Comment by Edwhis** [comment]
Any news on this? I still not able to vertically center hint.

**Comment by kassim** [comment]
Here's an attempt at a fix for this
https://stackoverflow.com/a/50798196/2233621

**Comment by CoreyPedestrian** [comment]
Are there any updates on this or ETA on when shapes theming will be introduced on text fields?

**Comment by mayken** [comment]
Any news on this?

**Comment by shubhambansal** [comment]
Hey Guys, I have also faced this issue and looking for some custom library or some optimal solution.

**Comment by ekussberg** [comment]
Hey @afohrman, any news regarding the ETA of the fix for this bug?

**Comment by Shirane85** [comment]
This bug make TextInputLayout looks bad and not useable for our design. We had to move back to a regular edit text. Hope you guys fix this soon. (7 months old !)

**Comment by Dwite** [comment]
Well, you can fix it by setting correct paddings on the style but would be great to have it by default.

**Comment by Shirane85** [comment]
@Dwite We tried many attributes but nothing worked. What excactly works for you?

**Comment by alexandrupele** [comment]
Just tried with AndroidX and 'com.google.android.material:material:1.1.0-alpha02' and it still doesn't seem to be fixed - can anybody else confirm this?

**Comment by afohrman** [comment]
You can fix it by setting android:padding on the TextInputEditText/TextInputEditText style. Fixing it in the TextInputEditText style is blocked for now because fixing this issue causes a regression in the compound drawable. We're evaluating workarounds to mitigate/fix the issue, but in the meantime, I recommend setting android:padding on the TextInputEditText.

**Comment by PectoralisMajor** [comment]
@afohrman which value should we set it to? And shouldn't it be only paddingBottom?

**Comment by afohrman** [comment]
Any equivalent values for the top and bottom should visually center the label. Since `android:paddingTop` is set to `20dp` in `Widget.MaterialComponents.TextInputEditText.FilledBox`, you can set `android:paddingBottom` to `20dp` as well to center the label.

I recommend setting both `android:paddingTop` and `android:paddingBottom` to ensure that if/when the values change in the style, your text field is still visually centered.

**Comment by ekussberg** [comment]
I reported bug in the main repo: https://issuetracker.google.com/issues/122553583

**Comment by broakenmedia** [comment]
Hoping to see a solution or even a workaround for this soon.

**Comment by alexandrupele** [comment]
Yep - still waiting...

**Comment by zekapp** [comment]
This part works perfect as expected in the library for ios platform. Is it a joke Google

**Comment by mayken** [comment]
Problem is fixed!
https://issuetracker.google.com/issues/122553583#comment11

**Comment by broakenmedia** [comment]
Which release should the fix be included in? Alpha 06? Still seeing the same issue at the moment.

**Comment by zmeeagain** [comment]
Alpha 06 seems to still have issues with aligning the hint in TextInputEditText.

**Comment by leticiarossi** [comment]
Where do you see issues?

**Comment by zmeeagain** [comment]
Can align hint text start, center and right, but does not seem to be able to do so vertically. Unless that is the intended behaviour.

**Comment by vadimleonov** [comment]
What about fix ?

**Comment by trevorhackman** [comment]
This seems to still be an issue.

**Comment by afohrman** [comment]
The filled text field looks fine on our end:
![image](https://user-images.githubusercontent.com/13263374/75286118-e9365200-57e5-11ea-8acf-6b932023b136.png)

Please test with the latest version and if you still see alignment issues, please provide a screenshot and source code for your use case. Thank you!

**Comment by whereareu** [comment]
android:paddingTop="18dp"
 android:paddingBottom="18dp"
 put them in the TextInputEditText

**Comment by Bharath-android** [comment]
it's work for me @whereareu 
Thank you.

**Comment by sdfgsdfgd** [comment]
android:paddingTop="0dp"
            android:paddingBottom="0dp"
            
            
            this works better
