### ISSUE TITLE
Tinting the background of an outlined Material Components button

### ISSUE THREAD

**Issue by zsmb13** [material-components/material-components-android#129]
### Overview

I'm trying to create an outlined Material Components button, however I need it to have a semi-transparent background in addition to the stroke. This is my code so far:

```xml
<android.support.design.button.MaterialButton
    android:id="@+id/foo"
    style="@style/Widget.MaterialComponents.Button.TextButton"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="Button"
    app:backgroundTint="#CFFF"
    app:strokeColor="@color/colorAccent"
    app:strokeWidth="2dp" />
```

The issue is that the background shows some white pixels outside the stroke:

![image](https://user-images.githubusercontent.com/12054216/40668347-87d164ae-6364-11e8-97d6-a28c8eee0689.png)

The amount of pixels that are visible around the button increase as the stroke width increases, for example with a larger, 5dp stroke:

![image](https://user-images.githubusercontent.com/12054216/40668385-a2a486e4-6364-11e8-9b66-e05848a9aca7.png)

### Reproduction steps

Create a layout including the XML code above.

### Version number

Support library version `28.0.0-alpha1`

### Operating system and device

OP5T on 8.1 Oreo, but also multiple emulators and the Android Studio preview

**Comment by ldjcmu** [comment]
Thanks for this report. I've created this ticket for tracking: https://issuetracker.google.com/issues/120656527. I know we have seen issues with how the corner radius applying differently to the stroke versus the shape can case an issue, so hopefully we'll have an update soon.

**Comment by ldjcmu** [comment]
This issue should be fixed in alpha release 2 coming out next week.

**Comment by ViHtarb** [comment]
Hi. This issue is not fully fixed. Now i`m using 1.1.0-alpha07 and have same issue. Look at left and right bottom corners.
![Снимок](https://user-images.githubusercontent.com/8938207/59164729-ec839380-8b19-11e9-8b00-9ae9ed08c336.PNG)

button style:
```xml
<style name="Widget.Button" parent="Widget.MaterialComponents.Button.UnelevatedButton">
        <item name="cornerRadius">@dimen/btn_corner_radius</item>
</style>
```
button in layout:
```xml
<com.google.android.material.button.MaterialButton
                android:id="@+id/status_button"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:paddingBottom="10dp"
                android:paddingEnd="12dp"
                android:paddingStart="12dp"
                android:paddingTop="10dp"
                android:textAppearance="@style/TextAppearance.MaterialComponents.Subtitle1"
                app:strokeColor="@color/charcoalGrey"
                app:strokeWidth="2dp"
                tools:icon="@drawable/ic_order_closed"
                tools:text="@string/order_status_closed_title"/>
```
