### ISSUE TITLE
Long text cutting off in BottomNavigationView

### ISSUE THREAD

**Issue by GrzegorzFeather** [material-components/material-components-android#139]
### Overview

Long texts cut off in BottomNavigationView only when tab is selected. When tab is unselected, it displays the text properly

#### When tab is unselected (Meine tickets)
<img width="364" alt="screen shot 2018-06-08 at 08 45 31" src="https://user-images.githubusercontent.com/3044632/41167650-6c66d992-6af8-11e8-9fb0-f0df4032454c.png">

#### When tab is selected (Meine tickets)
<img width="363" alt="screen shot 2018-06-08 at 08 45 48" src="https://user-images.githubusercontent.com/3044632/41167652-6cb1489c-6af8-11e8-8082-d693343ca3bb.png">

### Reproduction steps

- Setup bottom navigation view with 5 menu items with titles as: "Starseite", "Suchen", "Meine Tickets", "Verkaufen", "Profil"
```
<menu
  xmlns:android="http://schemas.android.com/apk/res/android">
  <item
    android:id="@+id/action_home"
    android:icon="@drawable/tab_home_icon_selector"
    android:title="@string/nav_tab_home"/>

  <item
    android:id="@+id/action_explore"
    android:icon="@drawable/tab_explore_icon_selector"
    android:title="@string/nav_tab_explore"/>

  <item
    android:id="@+id/action_my_tickets"
    android:icon="@drawable/tab_tickets_icon_selector"
    android:title="@string/nav_tab_my_tickets"/>

  <item
    android:id="@+id/action_sell"
    android:icon="@drawable/tab_sell_icon_selector"
    android:title="@string/nav_tab_sell"/>

  <item
    android:id="@+id/action_profile"
    android:icon="@drawable/tab_profile_icon_selector"
    android:title="@string/nav_tab_profile"/>
</menu>
```

- View style is:
```
<com.google.android.material.bottomnavigation.BottomNavigationView
    android:id="@+id/home.navigation"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:labelVisibilityMode="labeled"
    app:menu="@menu/home"/>
```

### Version number

 - Found in version 1.0.0-alpha3

### Operating system and device

 - Found in Nexus 5X emulator running Android Oreo

![screen shot 2018-06-08 at 08 55 37](https://user-images.githubusercontent.com/3044632/41168086-c20d5b86-6af9-11e8-8260-d42da7e1d01f.png)

**Comment by ppthakur** [comment]
Please add this property in your Xml
app:labelVisibilityMode="selected"

**Comment by kistitan** [comment]
I am also facing this issue.

labelVisibilityMode ="labeled" should work too especially if active and inactive text size are the same.
It feels a bit strange that text get truncated just because the text color is changed.

Would you mind reconsidering reopening this issue?

**Comment by t7costa** [comment]
Agreed. I'm not sure why this extra padding is needed in "labeled" mode https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/res/layout/design_bottom_navigation_item.xml#L45

**Comment by viktorsator** [comment]
Same goes for me. It would be nice to have this fixed... As @t7costa said i'm not sure why did they put an extra padding on the largeLabel...

**Comment by kistitan** [comment]
As for now I use this for the active childView:

            BottomNavigationItemView itemView = (BottomNavigationItemView) childView;
            View activeLabel = itemView.findViewById(com.google.android.material.R.id.largeLabel);
            if (activeLabel != null && activeLabel instanceof TextView) {
                ((TextView)activeLabel).setPadding(0,0,0,0);
            }

But it is not the ideal, would be nice if we had an official API to influence this.
I do not see anything on the material design website about padding for active item, so it looks a deviation for me.

**Comment by chris-tipton** [comment]
@kistitan When do you call that code to reset the padding? I tried it in a OnNavItemSelectedListener, but I found that function needs to return before the largeLabel becomes active.

**Comment by krobitai** [comment]
Would like this reopened as well.  Facing the same issue and it doesn't seem to have a reason that it needs to work this way.

**Comment by ldjcmu** [comment]
This issue is being tracked at https://issuetracker.google.com/issues/115754572

**Comment by kaustavjaiswal** [comment]
Till Google Fixes this, I was able to to use @kistitan 's solution and also add this to the mix to help truncate the text properly in Kotlin:
`activeLabel.ellipsize = TextUtils.TruncateAt.END
  baselineChild.setPadding(0, 0, 0, 0)`

**Comment by mapo-lp** [comment]
@kistitan and @kaustavjaiswal's solutions works like a chaaarm, thanks!

**Comment by afohrman** [comment]
This is being tracked in the Issue Tracker: https://issuetracker.google.com/115754572

**Comment by sagrawal2418** [comment]
public void disableShiftMode() {
        BottomNavigationMenuView menuView = (BottomNavigationMenuView) bottomNavigationView.getChildAt(0);

        for (int i = 0; i < menuView.getChildCount(); i++) {
            BottomNavigationItemView item = (BottomNavigationItemView) menuView.getChildAt(i);
            View activeLabel = item.findViewById(R.id.largeLabel);
            if (activeLabel instanceof TextView) {
                activeLabel.setPadding(0, 0, 0, 0);
            }
        }
    }

**Comment by nisd93** [comment]
@sagrawal2418  works like a charm

**Comment by DimasDark** [comment]
> BottomNavigationMenuView menuView = (BottomNavigationMenuView) bottomNavigationView.getChildAt(0);

use this in combination with @DhanalakshmiS answer, it works perfectly:


    
    <dimen name="design_bottom_navigation_text_size" tools:override="true">12sp</dimen>
    <dimen name="design_bottom_navigation_active_text_size" tools:override="true">12sp</dimen>

**Comment by Ghedeon** [comment]
Thanks, @FK1453, seems like the cleanest solution so far.

**Comment by deathstroke007** [comment]
Thanks for the Workaround. For those coming to here for the solution, it is working perfectly.

**Comment by palmas** [comment]
Thanks, @fatihkizmaz , works like a charm!=)

**Comment by mehdiyari** [comment]
app:labelVisibilityMode="unlabeled"
this line of code on 'com.google.android.material.bottomnavigation.BottomNavigationView' work for me

**Comment by ademar111190** [comment]
@kistitan and @sagrawal2418 workaround adapted for kotlin:

```
val menuView = bottom_navigation_view.getChildAt(0) as? ViewGroup ?: return
menuView.forEachChild {
  it.findViewById<View>(R.id.largeLabel)?.setPadding(0, 0, 0, 0)
}
```

**Comment by saharshpruthi** [comment]
Upgrading to `com.google.android.material:material:1.1.0-beta01` will fix this issue.

- reference : [https://issuetracker.google.com/issues/115754572#comment14](url)

**Comment by rafabaptista** [comment]
> <item name="design_bottom_navigation_item" type="layout" tools:override="true">@layout/bottom_navigation_item</item>

Perfect!

**Comment by rahul-rahul1** [comment]
bottomNavigation Icon by default is showing black-color.How resoved the icon issue in bottomNavigationView android?

**Comment by paulshandomain** [comment]
Upgrading to com.google.android.material:material:1.1.0 will fix long text cutting off bug.

**Comment by Mr-Ramzan** [comment]
In this theme => Theme.MaterialComponents.Light.NoActionBar.
         
     <dimen name="design_bottom_navigation_text_size" tools:override="true">8sp</dimen>
    <dimen name="design_bottom_navigation_active_text_size" tools:override="true">8sp</dimen>
does not worked for me.
What I did to resolve is 

    <style name="BottomNavigationView.InActive" parent="@style/TextAppearance.AppCompat.Caption">
        <item name="android:textSize">8sp</item>
    </style>

    <style name="BottomNavigationView.Active" parent="@style/TextAppearance.AppCompat.Caption">
        <item name="android:textSize">8sp</item>
    </style>

Define these in styles and used in the XML like below.

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/nav_view"
        ...........
        app:itemTextAppearanceActive="@style/BottomNavigationView.Active"
        app:itemTextAppearanceInactive="@style/BottomNavigationView.InActive"
        .......
        android:theme="@style/BottomNavigationTheme"
        />
Hope its helpful to someone.

**Comment by manishakamble** [comment]
@paulshandomain  its work

**Comment by jinpang** [comment]
Reset BottomNavigationItemView long click listener, can resolve long text cutting off in BottomNavigationView. e.g:
BottomNavigationItemView[] views = dataBinding.bottomNav.getBottomNavigationItemViews();
        for (BottomNavigationItemView v : views) {
            if (v != null) {
                v.setOnLongClickListener(v1 -> true);
            }
        }

**Comment by MichaelTheBestProgrammerInTheWorld** [comment]
It's fixed now all what you need is to upgrade the version as the following
implementation 'com.google.android.material:material:1.1.0'

**Comment by georgious1** [comment]
Issue still reproducable in implementation 'com.google.android.material:material:**1.2.1**'

**Comment by outofsleepexception** [comment]
Having the same issue with '1.3.0-alpha03'.

**Comment by abhishekgargx** [comment]
It will remove default padding, center align text
 and add support for two lines, so in case of long text it will appear in two lines. 

this will work with old as well new material library.

```
private void updateBottomViewProperties() {
        BottomNavigationMenuView menuView = (BottomNavigationMenuView) bottomNavigationView.getChildAt(0);
        if (menuView != null) {
            for (int i = 0; i < menuView.getChildCount(); ++i) {
                BottomNavigationItemView item = (BottomNavigationItemView) menuView.getChildAt(i);
                if (item != null) {
                    setBottomNavTextViewProps(item.findViewById(R.id.smallLabel));
                    setBottomNavTextViewProps(item.findViewById(R.id.largeLabel));
                }
            }
        }
    }

    private void setBottomNavTextViewProps(View view){
        if (view instanceof TextView) {
            view.setPadding(0, 0, 0, 0);
            view.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);
            ((TextView) view).setGravity(Gravity.CENTER);
            ((TextView) view).setMaxLines(2);
        }
    }
```
