### ISSUE TITLE
[Motion] Shared Axis transitions are broken with Fragment 1.3.0-beta01

### ISSUE THREAD

**Issue by ansman** [material-components/material-components-android#1771]
**Description:**
There are visual issues with the shared axis transitions when using Fragment 1.3.0-beta01

**Expected behavior:** 
[device-2020-10-02-174713.mp4.zip](https://github.com/material-components/material-components-android/files/5320447/device-2020-10-02-174713.mp4.zip)

**Source code:** I used the catalog app with the fragment version set to 1.3.0-beta01

**Android API version:** 30

**Material Library version:** Latest master (d88ff770be2fd0041a82ca4ae2d6000136e0eada)

**Device:** Google Pixel 4XL

**Comment by hunterstich** [comment]
Hey Nicklas,

It looks like this is a known issue with Fragment 1.3.0* - https://issuetracker.google.com/issues/169874632 - likely caused by something related to https://android.googlesource.com/platform/frameworks/support/+/47c5e9d30d0304a7d1ac6a522c01a055b858ff28%5E%21/#F4.

I spoke with the AndroidX team and they said this should be solved once the above bug is fixed.

In the meantime, are you able to use Fragment 1.2.x?

**Comment by ansman** [comment]
Unfortunately we've already migrated to the new fragment result listeners so down grading isn't an option at this point.

**Comment by hunterstich** [comment]
Hey @ansman,

Any chance you're able to verify this is fixed with Fragment `1.3.0-beta02`?

**Comment by ansman** [comment]
@hunterstich Sorry for the long response time but I just got a chance to try this. The issue still persists with `1.3.0-rc01`. The outgoing fragment animates just fine but the incoming fragment doesn't animate at all.

**Comment by hunterstich** [comment]
Hmm, yea I can reproduce this as well. 

I'll try to figure out what's going on.

**Comment by kdrag0n** [comment]
I think this is the same underlying bug as #1984, but the visual effects are different depending on the views used in the incoming fragment.

Examples of behavior with other views: [RecyclerView](https://streamable.com/h9m2cx) and [ScrollView](https://streamable.com/rfawk6)

RecyclerView animates incorrectly and looks like it's strecthed. ScrollView has an exaggerated content animation and the scrollbar appears immediately without an animation, similar to the demo posted above.

A workaround is to set a solid background for the fragment:
```kotlin
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Workaround for AndroidX bug: https://github.com/material-components/material-components-android/issues/1984
        view.setBackgroundResource(R.drawable.solid_background)
    }
```

res/drawable/solid_background.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<color xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="?android:attr/colorBackground" />
```

I'm not sure why this helps, but it gets the job done. Perhaps the animation scales are being calculated before the inner views are fully initialized, and the workaround fixes it by forcing the fragment's view to occupy all the space in the container immediately?

Correct behavior with the workaround: [RecyclerView](https://streamable.com/8hgdc5) and [ScrollView](https://streamable.com/o5f93i)

**Comment by iRYO400** [comment]
How is it going? Still exists in `1.3.2`

**Comment by pubiqq** [comment]
I got this issue after recent appcompat update from 1.1.0 to 1.4.0:

<table>
  <tr>
    <th>Appcompat 1.1.0<br />(before 4d4f3cc)</td>
    <th>Appcompat 1.4.0<br />(after 4d4f3cc)</td>
   </tr> 
   <tr>
      <td><video src="https://user-images.githubusercontent.com/82187521/168605228-6b35366a-1f6a-4259-a1f3-af3de267bb6a.mp4" /></td>
    <td><video src="https://user-images.githubusercontent.com/82187521/168605350-4c6008aa-becd-490f-8b51-298be44bc155.mp4"></td>
  </td>
  </tr>
</table>

**Comment by pubiqq** [comment]
The future has come, and after 4d4f3cc the issue turned into a full-fledged regression:

<table>
  <tr>
    <th>Appcompat 1.1.0<br />(before 4d4f3cc)</td>
    <th>Appcompat 1.4.0<br />(after 4d4f3cc)</td>
   </tr> 
   <tr>
      <td><video src="https://user-images.githubusercontent.com/82187521/168605228-6b35366a-1f6a-4259-a1f3-af3de267bb6a.mp4" /></td>
    <td><video src="https://user-images.githubusercontent.com/82187521/168605350-4c6008aa-becd-490f-8b51-298be44bc155.mp4"></td>
  </td>
  </tr>
</table>
