### ISSUE TITLE
[TextInputLayout] Hint (label) cut by the outline border when gravity is set to "end"

### ISSUE THREAD

**Issue by KKH-tw** [material-components/material-components-android#2277]
**Description:**

In a `TextInputLayout`, after `android:gravity="end"` being set for the `TextInputEditText,` when the text field is clicked and the hint (label) is automatically moved to the outline border, the position of the hint (label) is **too right**, causing the right-most part of it to be **cut by the border**. This behavior happens most of the time, not always. As shown below:

![投影片1](https://user-images.githubusercontent.com/42627483/123535418-39b11d00-d756-11eb-88c0-30275a2dfe80.JPG)

**Expected behavior:**

But when the text field is **clicked again**, the hint (label) moves to the **appropriate positio**n, which is the expected behavior (if it happens right after the first click), as shown below:

![投影片2](https://user-images.githubusercontent.com/42627483/123535442-5a797280-d756-11eb-90ca-e0a7dd67bb58.JPG)

**Source code:**

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/layout1"
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:hint="Hint is cut here"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintStart_toStartOf="parent" >

        <com.google.android.material.textfield.TextInputEditText
            android:gravity="end"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.google.android.material.textfield.TextInputLayout>

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/layout2"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@id/layout1"
        android:hint="Hint is cut here"
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox" >

        <com.google.android.material.textfield.TextInputEditText
            android:gravity="end"
            android:layout_width="match_parent"
            android:layout_height="match_parent"  />

    </com.google.android.material.textfield.TextInputLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Android API version:**
28 (HTC U11+, physical device)
30 (emulator)

**Material Library version:**
1.3.0

**Comment by drchen** [comment]
I can't reproduce it. Can you try to update to the latest library version?

**Comment by KKH-tw** [comment]
> I can't reproduce it. Can you try to update to the latest library version?

It uses the latest libraries. The repo is here:
https://github.com/KKH-tw/test2

**Comment by drchen** [comment]
I think it's been fixed with 
https://github.com/material-components/material-components-android/commit/87b50c6aee240659841a7d5f2e52c1a6324d611f

Which will be released today. : )

**Comment by KKH-tw** [comment]
> I think it's been fixed with
> [87b50c6](https://github.com/material-components/material-components-android/commit/87b50c6aee240659841a7d5f2e52c1a6324d611f)
> 
> Which will be released today. : )

I just updated the dependency (the github repo has been updated, too) to `implementation 'com.google.android.material:material:1.5.0-alpha01'`, but the problems is still there.

**Comment by KKH-tw** [comment]
A screen recording is here:

https://user-images.githubusercontent.com/42627483/125099148-4c3e3580-e10a-11eb-9e08-86d8bb020b51.mp4

**Comment by drchen** [comment]
ok let me reopen the issue and see what I can figure out.
