### ISSUE TITLE
[MaterialCardView] Render error.

### ISSUE THREAD

**Issue by shwoghk14** [material-components/material-components-android#3136]
**Description:** Full description of issue here
When I update material version 1.8.0-alpha02 or upper, Preview is not showing and show error log in layout manager.
below is log message.

```
java.lang.IllegalArgumentException: Motion easing theme attribute must be an @interpolator resource for ?attr/motionEasing*Interpolator attributes or a string for ?attr/motionEasing* attributes.
	at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:74)
	at com.google.android.material.card.MaterialCardViewHelper.<init>(MaterialCardViewHelper.java:161)
	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:174)
	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:160)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected behavior:** Screenshots and/or description of expected behavior
Can see in preview.

**Source code:** The code snippet which is causing this issue
```
<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:text="test"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

</com.google.android.material.card.MaterialCardView>
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** Android API version here
API 33

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.8.0-alpha02 ~ 1.8.0-beta01 (upper)

**Device:** Device on which the bug was encountered here
android studio Dolphin 2021.3.1 Patch 1

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ekoo** [comment]
Also happen on AppBarLayout using Android Studio Dolphin
![Screenshot from 2022-12-13 12-31-13](https://user-images.githubusercontent.com/35864865/207234861-98bf4117-07a8-4578-9fa3-c5db82798231.png)

**Comment by imhappi** [comment]
This is a known issue with Android Studio (see comment thread in this issue https://github.com/material-components/material-components-android/issues/3007). Seems to have been fixed in the latest canary build

**Comment by cloewen8** [comment]
Still appears to be present in Android Studio Electric Eel (as well as IntelliJ IDEA 2023.1) with Material components 1.10.0 alpha 1. No error is present in Android Studio (just an empty preview), whoever the exact error above does appear in Intellij IDEA (also no preview). Switching out the MaterialCardView causes the error to disappear and the preview to work correctly.
