### ISSUE TITLE
[MaterialButton] Ripple cannot be removed on api level 33

### ISSUE THREAD

**Issue by dominicmarmionswrve** [material-components/material-components-android#3370]
**Description:** 
A dark color is added to MaterialButtons that are in focused state. It would appear that the default ripple is causing the dark color and removing this by setting it to null _should_ remove this added shade. However this only works for devices on api level 32 and below. 

**Expected behavior:** 
The gif shows this issue on two emulators with expected behaviour on the left (api level 32) and unexpected behaviour on the right (api level 33). The arrows keys are on keyboard are used to bring the buttons into and out of focus. The text and border appear yellow when in focus, but the background should remain same color.

![focus_state_and_ripple1](https://user-images.githubusercontent.com/9349545/235692316-3987f570-f24f-4b9c-b10c-6b54c5dc06bc.gif)

**Additional context:** 
The buttons are dynamic and configured programmatically. The issue was first noticed when the focus state appeared darker on all emulators. Calling `setRippleColor(null)` via [this api](https://developer.android.com/reference/com/google/android/material/button/MaterialButton#setRippleColor(android.content.res.ColorStateList)) removed the unwanted darkness on api level 32 and below. Can't seem to remove it on api level 33. The issue might be related to [this already closed issue](https://github.com/material-components/material-components-android/issues/3061)?

**Material Library version:** 
com.google.android.material:material:1.8.0

**Comment by dsn5ft** [comment]
Hi @dominicmarmionswrve this was a bug a RippleDrawable on T which is part of the Android framework itself. I believe it has been addressed already, but you might need to try physical T devices to see the fix. It should also not be an issue going forward on future versions of Android.

**Comment by dominicmarmionswrve** [comment]
Just to note for posterity, I've updated a real physical pixel 4a to latest Android version and the bug is still there. (I used `adb shell input keyevent 20` to move focus on a mobile device).

I think this might be the reported issue? --> https://issuetracker.google.com/issues/267563676

I'll keep an eye for updates in the issuetracker.

Thanks @dsn5ft
