### ISSUE TITLE
MaterialAlertDialogBuilder font size error

### ISSUE THREAD

**Issue by rulogarcillan** [material-components/material-components-android#354]
When i use dialog.builder the font size is correct but when i use  MaterialAlertDialogBuilder the font size of body text is smaller. its ok?

`    implementation 'com.google.android.material:material:1.1.0-alpha06'`

Im use this theme 
   ` <style name="AppTheme" parent="Theme.MaterialComponents.Light">`

MaterialComponent

`         MaterialAlertDialogBuilder(this)
            .setMessage("This is a test of MaterialAlertDialogBuilder")
            .setPositiveButton("Ok", null)
            .show()`

![Screenshot_20190512-115103_2](https://user-images.githubusercontent.com/4234249/57580751-cda7c800-74ad-11e9-832a-63f7dac74514.jpg)

AlertDialog.Builder

```
AlertDialog.Builder(this)
            .setMessage("This is a test of AlertDialog.Builder")
            .setPositiveButton("Ok", null)
            .show()
```

![Screenshot_20190512-115241_2](https://user-images.githubusercontent.com/4234249/57580768-034cb100-74ae-11e9-80c8-904707265fb0.jpg)

Where is the problem?

**Comment by SteinerOk** [comment]
Problem is here:
```
<style name="Base.MaterialAlertDialog.MaterialComponents.Title.Text" parent="RtlOverlay.DialogWindowTitle.AppCompat">
    <item name="android:textAppearance">?attr/textAppearanceSubtitle1</item>
</style>
```
Must be:
```
<style name="Base.MaterialAlertDialog.MaterialComponents.Title.Text" parent="RtlOverlay.DialogWindowTitle.AppCompat">
    <item name="android:textAppearance">?attr/textAppearanceHeadline6</item>
</style>
```
And here:
```
    <style name="MaterialAlertDialog.MaterialComponents.Body.Text" parent="TextAppearance.MaterialComponents.Body2">
    <item name="android:textAppearance">?attr/textAppearanceBody2</item>
  </style>
```
Must be (+incorrect parent style):
```
    <style name="MaterialAlertDialog.MaterialComponents.Body.Text" parent="TextAppearance.MaterialComponents.Body1">
    <item name="android:textAppearance">?attr/textAppearanceBody1</item>
  </style>
```

**Comment by rulogarcillan** [comment]
Will it be fixed in the next version?

**Comment by ldjcmu** [comment]
This is completely intentional based upon our current design guidance. I do know the design team is considering updates to the Dialog styles (and will update material.io at that time too). Once design decides, we may make changes to textAppearance, but for now, this is how they are designed to look.

Feel free to override the used styles with different textAppearances if it servers your app's design.

**Comment by timautin** [comment]
So, more than one year later, can we have an update on the situation?

From my findings:

- Material.io (https://material.io/components/dialogs) and Android 10 still shows the "old" style
- MaterialAlertDialogBuilder & Android 11 emulator build dialogs with "new" style, but with differences:
  - Android 11 dialogs content text is black rather that colorOnSurface at 60% opacity
  - Android 11 dialogs buttons are no longer bold & upper cased
- material-components Github page (https://github.com/material-components/material-components-android/blob/master/docs/components/Dialog.md) shows a mix of styles :vomiting_face: 

What are we supposed to do with that?
