### ISSUE TITLE
[Material3 Colors] Version 1.11.0 Components doesnt respect the system colors

### ISSUE THREAD

**Issue by ytheekshana** [material-components/material-components-android#3924]
Hi. I was using version 1.10.0 and it worked perfect. My device is a Samsung S22 Ultra with One UI 6 (Android 14)
So my accent color was a brownish color and with the version 1.10.0, material components was also matched to that color. Today I updated to version 1.11.0 and suddenly the component doesn't respect my system accent color. material components was in a color of blue or something. Looks like the app identified the primaryColor as light blue. How is this possible?

Also I was using the Android 14 emulator and this is not happening in that. Happens only on my device. 
Here are two screenshots.

Is this an issue on my end? If it is could you point me a way to fix this?

![1 10 0](https://github.com/material-components/material-components-android/assets/24976965/7d434edc-86cb-4be0-a4d5-46b799d20fe1)
This one is with 1.10.0

![1 11 0](https://github.com/material-components/material-components-android/assets/24976965/9cddbde0-c04a-413a-a368-8f2150a2823f)
this one is with 1.11.0

**Comment by dsn5ft** [comment]
@pekingme can you take a look at this?

Also @ytheekshana do you have any devices other than Samsung to test on?

**Comment by ytheekshana** [comment]
No. Just this Samsung. I'll try to find another.

**Comment by ytheekshana** [comment]
I have noticed,  Gmail, Drive, and also play store which worked perfectly before has now turned blue. May be they too have updated to 1.11.0

**Comment by pekingme** [comment]
@ytheekshana On 1.11.0, we use the new color roles from system UI (e.g., `@android:color/system_primary_dark`) for dynamic colors on Android U. Samsung OneUI has this ability to adjust the "Color palettes". I believe behind the scene, they override the sysUI color roles. Could you verify if you get the desired colors by enabling the "Color palettes" (Settings --> Wallpaper and style --> Color palette --> Color palette)? Without enabling this, the system UI primary color is blue-ish by default.

**Comment by ytheekshana** [comment]
yes I have enabled Color palettes and my accent color is nor a brownish color like in the first screenshot. but when updated to 1.11.0 material components are in a blueish color

**Comment by henrichg** [comment]
Yes, not working:

`android:theme="@style/Theme.Material3.DynamicColors.DayNight"`

and also:

`Context dynamicColorContext = DynamicColors.wrapContextIfAvailable(context, R.style.ThemeOverlay_Material3_DynamicColors_DayNight);
`

**Comment by pekingme** [comment]
Here're some captures on my Samsung Note 20 (One UI 5.1). It seems the system `primary`, `secondary`, `tertiary` palettes have similar hues to the **bottom** three colors shown in the palette thumbnail. The **top** three colors, though, should be Samsung color roles, which are only visible in Samsung apps. I think there could be some issues with the OEM overridden colors. Will ask around, stay tuned.

Color palette 1:
![material color 1](https://github.com/material-components/material-components-android/assets/8545955/9e75625c-7b52-429c-aa1c-7eb04f6c47ef)
![palette 1](https://github.com/material-components/material-components-android/assets/8545955/8af5166c-766c-44a6-aee8-215c7fa169d0)

Color palette 2:
![material color 2](https://github.com/material-components/material-components-android/assets/8545955/9d25a1c5-b674-4bea-b3d3-44a946a2e46e)
![palette 2](https://github.com/material-components/material-components-android/assets/8545955/18644643-aa86-49bd-ab95-1571d89746d3)

**Comment by ytheekshana** [comment]
Tried my app on Note20U with One UI 5.1. 
The issue is not visible there. Material Components respect the system colors. So this should be a One UI 6 problem right?

**Comment by henrichg** [comment]
Tested in my devices version 1.11.0:

Pixel 3a, Android 12 - colors are respected
Pixel 6, Android 14, latest december beta - colors are respected
Xiaomi 13 lite, Android 13, latest update - colors are respected
Redmi Note 9 pro, Android 12, latest update - colors are respected
Redmi Note 12 pro, Android 13, latest update - colors are respected
OnePus 9, Android 13, latest update - colors are respected

Galaxy S21, One UI 6, Android 14, letest december update - colors are NOT respected, BUT version 1.10.0 working good!

**Comment by pekingme** [comment]
I think I misunderstood the issue earlier. It seems that the dynamic colors don't apply properly on OneUI 6 with 1.11.0. Let me check if there's anything suspicious between 1.10 and 1.11.

**Comment by pekingme** [comment]
@ytheekshana Could you provide the following context with your device (Samsung S22 Ultra with One UI 6 (Android 14))? 

- A screenshot of the main color demo in Material's catalog (Color --> Demo)
- The clipboard contents when click the "copy" icon (top-right corner) in the dynamic palette demo (Color --> Dynamic Palette Demo).

**Comment by ytheekshana** [comment]
Currently far away from my PC. do you have an APK file of this catalog. So I can give the screenshots ASAP

**Comment by shizheng233** [comment]
I updated my phone's software version and the issue was resolved. My phone is Samsung Z Filp 4. The version used by Material3 Compose is 1.2.0-rc01, and the version of this Components is 1.11.0. The former mentioned in the update that `Dynamic color now pulls from system defined color roles. This improves contrast for accessible content, and more closely aligns dynamic color to the Material spec.` So it will also cause this problem.

Sorry for my poor English, I am not a native speaker.

**Comment by henrichg** [comment]
In my Galaxy S23, latest january firmware, v1.11.0. dynamic colors not working, v1.10.0 working.

**Comment by shizheng233** [comment]
> In my Galaxy S23, latest january firmware, v1.11.0. dynamic colors not working, v1.10.0 working.

I find it also not working now. If I change the scheme, the software colors will not change.

**Comment by zacharee** [comment]
It looks like Samsung isn't overriding the new resource values properly. `system_primary_dark` doesn't change while `system_accent1_200` does, for instance.

**Comment by ytheekshana** [comment]
Tried this one one UI 6.1. The issue still exists.

**Comment by wattenre** [comment]
> I can confirm this as well in S22+ Android 14 (OneUI 6).
> I also noticed the same issue in Emulator with API 34 image but with emulator re-selecting the pallet fix the issue for all apps.

Can confirm, same on S23Ultra

**Comment by smanenti** [comment]
Same issue here, on Samsung S23 ultre, oneui 6, Android 14. 
All Google apps are affected and they are all displayed the default blue color, regardless of the selected color palet. Except the Gboard and Message app.

This issue is occurring since few months and Samsung is not fixing. Don't know if someone was able to find a workaround?

**Comment by ytheekshana** [comment]
Still persists on 1.12.0-beta01

**Comment by YangDai2003** [comment]
Same issue on Samsung s22 ultra, OneUI 6.0, Android 14.

**Comment by michelelorusso05** [comment]
Same problem on both Galaxy A33 and Galaxy Tab S8, on One UI 6.0. Do we really have to wait for a fix by Samsung?

**Comment by griffi-gh** [comment]
> Same problem on both Galaxy A33 and Galaxy Tab S8, on One UI 6.0. Do we really have to wait for a fix by Samsung?

I'm pretty sure Samsung's never going to fix it at this point, the best way around this is probably to build a workaround in the library itself

**Comment by ytheekshana** [comment]
Tried 1.13.0-alpha01 with S24U latest firmware. No luck

**Comment by abunayem** [comment]
Came across a similar issue with my Samsung A52, operating on OneUI 6.0 with Android 14

**Comment by griffi-gh** [comment]
Yep, same issue on both A52s and S21FE with OneUI 6

**Comment by itsmattking** [comment]
Same issue on Galaxy S23, Galaxy A53 both on Android 14 / OneUI 6.1 and OneUI 6.0 respectively

**Comment by soyfaii** [comment]
Same on A33. One UI 6.1 is in beta I think. I hope Samsung solves this with the update. Otherwise, a dynamic color setting is nonsense.

**Comment by totallygeekdom** [comment]
S22 ultra, I just updated to oneUI 6.1. Monet is still broken.

**Comment by tipa** [comment]
I just hit this problem myself and I'm surprised that there doesn't seem to be any effort in resolving this.

**Comment by Smeagol2069** [comment]
I just updated to the latest system update and it resolved the issue.
Prior to updating it was pink, now it is blue which matches my wallpaper.


System update information provided by Verizon -- My phone is Samsung S22 
```
System Update 34 
The details:

Release date: 06/12/2024
Android™ Security Patch Level: June 2024
Software Version: UP1A.231005.007.S901USQS5EXE3
```

![Screenshot_20240624_163511_Calendar](https://github.com/material-components/material-components-android/assets/78649849/204d189d-3be1-4d95-84df-b9b915efa638)

![309436553-5611c479-03f0-4cb5-a5a1-9d36e697eda6](https://github.com/material-components/material-components-android/assets/78649849/2984744e-95e8-472e-802a-e5952a7f6ed4)

**Comment by Smeagol2069** [comment]
> The blue color looks like the default blue in one UI 6 devices which did to changed with the wallpaper. Try changing the color and check if it changes with the wallpaper. Its highly unlikely that Samsung fixed this.

Oh no it's not a true fix. You are correct, it doesn't change. I'm grateful for this blue over the pink though 😅

**Comment by ytheekshana** [comment]
There's a quick fix for this whole thing to work. Go to the developer settings and set Contrast (its in the drawing category) to medium and then back again to standard. Now the colors should change with the wallpaper. But it will get reset if you turn off dynamic colors. 

> > The blue color looks like the default blue in one UI 6 devices which did to changed with the wallpaper. Try changing the color and check if it changes with the wallpaper. Its highly unlikely that Samsung fixed this.
> 
> Oh no it's not a true fix. You are correct, it doesn't change. I'm grateful for this blue over the pink though 😅

**Comment by Smeagol2069** [comment]
> There's a quick fix for this whole thing to work. **Go to the developer settings and set Contrast (its in the drawing category) to medium and then back again to standard.** Now the colors should change with the wallpaper. But it will get reset if you turn off dynamic colors.

I did that, now it's back to pink :/

Not sure what you mean by dynamic colors -- I see option for color palette for system ui -- is that it?

**Comment by ytheekshana** [comment]
hold the homescreen->wallpaper and style-> color pallet> turn it off and back on again and it should go to blue once again.

**Comment by bubbleguuum** [comment]
It is really unfortunate that dynamic colors (Material You) is broken on Samsung device that constitute the bulk of all Android devices...

**Comment by Szanik** [comment]
Same issue S21Fe ONE UI 6.1

Did the contrast trick, now my app is pink hahaha

**Comment by ytheekshana** [comment]
By turning off and turning on the dynamic colors you can go back to default blue. 
This is really a pain in the ass. Lets hope samsung will fix it in One UI 7

**Comment by michelelorusso05** [comment]
Even if they fix it in One UI 7.0, older versions will still be affected.
It seems like the only solution is to wait for Google to rollback the
previous (material components v1.10.0 I think) just for One UI devices, or
us to rollback the library to an older version...

Il Mer 24 Lug 2024, 14:47 Yasiru Nayanajith ***@***.***> ha
scritto:

**Comment by ytheekshana** [comment]
Its highly unlikely that Google will revert back the library

**Comment by michelelorusso05** [comment]
I was thinking of a workaround like if manufacturer is Samsung then use the
old behaviour

Il Mer 24 Lug 2024, 15:57 Yasiru Nayanajith ***@***.***> ha
scritto:

**Comment by yusufalqowy** [comment]
> Same issue S21Fe ONE UI 6.1 Android 14 Security Patch: 1.Juliy 2024 androidx.compose:compose-bom:2024.06.00 Did the contrast trick, now my app is pink hahaha

I'm using androidx.compose:compose-bom:2024.01.00 and previously dynamic color was working. After upgrading to androidx.compose:compose-bom:2024.06.00, dynamic color is no longer working. I think there might be an issue with the library.

**Comment by RyeGordo** [comment]
I also have this issue on my S22 Ultra.
No luck with `1.13.0-alpha04` despite what's mentioned in the release notes.

**Comment by long5436** [comment]
I also had the same issue and I created a library to solve this https://github.com/long5436/oneui6-material3-dynamic-color-compose

**Comment by BoD** [comment]
The root issue on Android's bugtracker: https://issuetracker.google.com/issues/332331850

Please star that one.

**Comment by ytheekshana** [comment]
Looks like ths issue is fixed in the One ui 6.1.1 in my S24 Ultra. Now the colors are applied to material you apps.

**Comment by michelelorusso05** [comment]
> Looks like ths issue is fixed in the One ui 6.1.1 in my S24 Ultra. Now the colors are applied to material you apps. 

Yes, it's mentioned in the patch notes; however, devices with OneUI 6.0 and 6.1 will still have the issue, so I still think a patch in the library is necessary

**Comment by michelelorusso05** [comment]
Tab S8: Monet now works correctly on One UI 6.1.1. Guess I'll have to wait for One UI 7 to receive the fix on my A33 though, as the 6.1.1 update is only for the AI devices

**Comment by pekingme** [comment]
This is a long thread! But fortunately, Samsung has deployed 6.1.1 which fixed the bug. I'll mark this issue as fixed. Thanks everyone for contributing the datapoint! 

@michelelorusso05 Could you check if there's a way to upgrade to 6.1.1? Based on a quick [search](https://sammyguru.com/your-guide-to-one-ui-6-1-1-new-features-and-supported-devices/), it seems 6.1.1 should be available for Tab S8.

**Comment by michelelorusso05** [comment]
> @michelelorusso05 Could you check if there's a way to upgrade to 6.1.1? Based on a quick [search](https://sammyguru.com/your-guide-to-one-ui-6-1-1-new-features-and-supported-devices/), it seems 6.1.1 should be available for Tab S8.

I said that the update fixed the issue on my Tab S8, however I still have this problem on my A33, which won't be updated until One UI 7.0 comes out

**Comment by pekingme** [comment]
Ah, misread your comment. It's interesting that Samsung put criteria on a patch upgrade. I'll follow up via our internal channel to find out the rationales here.

**Comment by BoD** [comment]
@pekingme I realize the issue is on Samsung's side, however in the meantime can Google implement a workaround in the library (the existence of https://github.com/long5436/oneui6-material3-dynamic-color-compose shows that it is possible)? This would avoid having to wait for a system update.

**Comment by pekingme** [comment]
The linked repo checks if the device is a Samsung with Android U then maps the colors to system dynamic palettes (like system_accent1_600) instead of system colors (like system_primary_light). This will make the material colors not responding to the Contrast Settings introduced in Android U. The system colors can switch to different palettes based on the contrast level.

**Comment by zacharee** [comment]
IMO it's better to have at least the color match what the user selected (or what the system selected from the wallpaper palette) even if the contrast profile isn't quite right vs. most apps just being blue. The version comparison is probably trickier now that there are versions of One UI that are based on Android 14 with proper Monet support, but it should be possible I think.

```kotlin
val isOneUI = Build.VERSION.SDK_INT >= Build.VERSION_CODES.P && (packageManager.hasSystemFeature("com.samsung.feature.samsung_experience_mobile") || packageManager.hasSystemFeature("com.samsung.feature.samsung_experience_mobile_lite"))
val isBeforeOneUI611 = (SystemProperties.get("ro.build.version.oneui")?.toIntOrNull() ?: 0) < 60101 // One UI 6.0 would be 60000, 6.1 would be 60100, 6.1.1 is 60101.

// if (isOneUI && isBeforeOneUI611) [retrieve pre-U palette tokens] else [normal logic]
```

SystemProperties needs reflection of course, but I know a lot of the support libraries use reflection for other things already.

**Comment by BoD** [comment]
@pekingme  I understand the reluctance but I agree with @zacharee that while it's not perfect, it would still be a lot better than the current situation.

**Comment by bubbleguuum** [comment]
Agreed that if a reasonable workaround can be made, it should. Yes, it is a Samsung problem, but there is probably not a single non-trivial app that does not have to work-around manufacturer specific issues.

**Comment by BoD** [comment]
So I guess that's a no?

This problem has been around since December of last year, this is mid October.

No sign of 6.1.1 on my Samsung S24.

A workaround in the library side is possible.

I'm usually a patient guy but I gotta say: this is annoying.

**Comment by BoD** [comment]
I just received an OTA update on my S24. 

And it's still not 6.1.1.

Can the decision to not do anything about this issue be reconsidered and this ticket be reopened please? Thanks!

**Comment by BoD** [comment]
Just got another OTA update. Could it be the one? Could it be an early Christmas gift?

Nope it's still 6.1.

My apps are still the wrong color.

Infinite sadness and pain.

**Comment by iamant92** [comment]
Is this fixed? or is there any work around? 
Need some help.
