### ISSUE TITLE
[Button] Vertical bar appers and gone on the right of button and textview's

### ISSUE THREAD

**Issue by kelalaka153** [material-components/material-components-android#4118]
This is a very strange behavior. I'm using bottom navigation and in one of the fragments (FA) there is a button. When the fragment is shown for the first time everything is normal. When we use bottom navigation to other fragments and then back to the FA, a vertical bar appears on the right of the button and then disappears in 3 seconds. This happens to buttons only with style using Widget.MaterialComponents.Button.OutlinedButton as parent style. Elevated is behaving as expected.

This is the style that the button uses

```
    <style name="ButtonTopGroupRight" parent="Widget.MaterialComponents.Button.OutlinedButton">
        <item name="iconPadding">8dp</item>
        <item name="fontFamily">@font/poppins</item>
        <item name="iconTint">@drawable/button_top_group_right_selector</item>
        <item name="strokeColor">@drawable/button_top_group_right_selector</item>
        <item name="android:textColor">@drawable/button_top_group_right_selector</item>

    </style>
```

**Expected behavior:** 

![button_submit_1](https://github.com/material-components/material-components-android/assets/46725068/6167a2fc-9d9e-4bbd-bed2-b6e3cd097cc1)

![button_submit_2](https://github.com/material-components/material-components-android/assets/46725068/359d8c0f-1cc7-48d8-ac6d-c3c843e20f36)

**Source code:** The code snippet which is causing this issue

This is the button.

```
            <com.google.android.material.button.MaterialButton
                android:id="@+id/addFilterButtonWide"
                style="@style/ButtonTopGroupRight"
                android:layout_width="140dp"
                android:layout_height="40dp"
                android:text="@string/common_filter"
                android:textColor="@color/black"

                android:layout_gravity="start"
                android:visibility="gone"
                />
```

**Android API version:** 

minSdk = 29
compileSdk = 34

**Material Library version:** 

material:1.11.0

**Device:**

Tested on Android 11,12 devices and Android 14 emulator.

**Comment by hunterstich** [comment]
Hi @kelalaka153,

Do you have a minimal sample app you can share with us that reproduces this? I don't see anything like this when trying to repro the issue on my end. Thanks!

**Comment by kelalaka153** [comment]
I'm trying to minimize the code. need little more time.

**Comment by langsmith** [comment]
@kelalaka153 , I also saw this (a couple of months ago). I doubt it's been fixed in the latest 1.12.0 version of Material. I put `android:scrollbars="none"` on the views that were showing the scrollbars 😕

**Comment by pekingme** [comment]
> @kelalaka153 , I also saw this (a couple of months ago). I doubt it's been fixed in the latest 1.12.0 version of Material. I put `android:scrollbars="none"` on the views that were showing the scrollbars 😕

That's interesting. Does it actually scroll if you, say, drag the label?

**Comment by kelalaka153** [comment]
@langsmith Yes, it still exists in 1.12.0 and your suggestion removes the issue. Kudos.

**Comment by pekingme** [comment]
Maybe also `wrap_content` the `layout_height`? Anyway, it seems not to be a MaterialButton issue. I'll close the issue.
