### ISSUE TITLE
[TextInputLayout] Material version of (AppCompat)AutoCompleteTextView

### ISSUE THREAD

**Issue by henrik-lindqvist** [material-components/material-components-android#470]
**Is your feature request related to a problem? Please describe.**
I need an `TextInputEditText` supporting auto-completion. Using `AppCompatAutoCompleteTextView` is possible but it lack the proper hint handling.

**Describe the solution you'd like**
Include an `TextInputAutoCompleteTextView` with the same workarounds implemented as `TextInputEditText`, or at least make `TextInputLayout.isProvidingHint()` public, see below.

**Describe alternatives you've considered**
I've made my own, by just copying the same hint workarounds, but is blocked by `TextInputLayout.isProvidingHint()` being package private, forcing me to resort to reflection.

**Comment by joaoeudes7** [comment]
recommend any alternatives?

**Comment by MGaetan89** [comment]
This is part of the library now, since [1.0.0-alpha06](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha06) if I'm not mistaken.
See [exposed dropdown menu](https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md#exposed-dropdown-menus).

**Comment by henrik-lindqvist** [comment]
@MGaetan89 No. I need the regular textfield with (multiple) auto-completion support, not a "spinner".

**Comment by consp1racy** [comment]
Is this about `MultiAutoCompleteTextView` or `AutoCompleteTextView`?

Since 1.2.0-alpha06 (April 2020), there is a `MaterialAutoCompleteTextView` which is automatically inflated instead of `AutoCompleteTextView` when using a `Theme.MaterialComponents.*`. If you don't use a material theme you'll need to reference the view by full class name in XML: `com.google.android.material.textfield.MaterialAutoCompleteTextView`.

Please, check if this fits your needs.

**Comment by henrik-lindqvist** [comment]
@consp1racy I made both, and was forced to place them in the `com.google.android.material.textfield` package to be able to access `TextInputLayout.isProvidingHint()` without using reflection. I always use full class names in my XML. If they're both now available in  v1.2.0-alpha06, great! I'll check em' out.

**Comment by drchen** [comment]
I think this is solved? I'll close this for now. Feel free to let us know if MaterialAutoCompleteTextView doesn't serve the need.

**Comment by henrik-lindqvist** [comment]
Material version of MultiAutoCompleteTextView, e.g. MaterialMultiAutoCompleteTextView, is still missing
