### ISSUE TITLE
[MaterialButton] buttons have background opacity when night mode set on pre-Q

### ISSUE THREAD

**Issue by lukaszkalnik** [material-components/material-components-android#514]
**Description:** When building an `AlertDialog` using `MaterialAlertDialogBuilder` with app theme inheriting from `Theme.MaterialComponents.DayNight.NoActionBar`, dialog's positive and negative buttons get background opacity. This happens only when night mode is set programmatically on pre-Q devices:
```
if (VERSION.SDK_INT < VERSION_CODES.Q) AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
```

![material_alert_dialog_buttons_background](https://user-images.githubusercontent.com/16528298/62780240-8a152800-bab5-11e9-9af4-9fa7f925b8d5.png)

**Expected behavior:** Dialog buttons background should be transparent (`TextButton` style).

**Source code:** 
Please see a minimum reproducible example app here:
https://github.com/lukaszkalnik/AlertDialogButtonsBackground

**Android API version:** API 27

**Material Library version:** 1.1.0-alpha09

**Device:** LG G7 Fit

**Comment by stefanmedack** [comment]
We encountered a similar issue while implementing dark mode features in our app. What helped us was setting `colorSurface` to `#010101` instead of `#000000`.

I did not yet find out what is the reason for that bug, though...

**Comment by dsn5ft** [comment]
Thanks for the report!

I tested locally using the latest build of our library and this issue should be fixed by https://github.com/material-components/material-components-android/commit/7f043206c0407e075f516a8cf4e3c5940d7f76bc (Update ElevationOverlayProvider compositeOverlay() to preserve original background color alpha), which will be included in a release coming soon.

**Comment by mrtcnnccn** [comment]
It is still a problem for same buttons inside Card Views. Please check it out.
