### ISSUE TITLE
[MaterialDatePicker] Allow other date formats when inserting date mannually.

### ISSUE THREAD

**Issue by ashley-figueira** [material-components/material-components-android#774]
When switching to keyboard input selection style, its only possible to input a date with the current format: MM/dd/yyyy.

I would like to be able to change the format on how users input date to something like dd/MM/yyyy which is more common in Europe.

**Comment by CoolMind** [comment]
At least, in 1.2.0-alpha06 in Russian locale it has been fixed.

**Comment by CoolMind** [comment]
In 1.2.0-alpha06 in Russian locale it formats "dd/MM/yyyy" (don't know, if it can be changed).

**Comment by drmrbrewer** [comment]
@ashley-figueira did you figure out a way of changing the date format?

**Comment by ashley-figueira** [comment]
> @ashley-figueira did you figure out a way of changing the date format?

@drmrbrewer nop. Before the date format would default to US date format. But that now has been fixed. So if you are in Europe i believe it will use the european date format. But there is still no way to change it afaik.

**Comment by drmrbrewer** [comment]
@ashley-figueira not sure if anything changed recently (I'm using the latest `1.3.0-alpha03`) but I'm still seeing manual input date in the form `MM/dd/yyyy` despite the fact that my device is and always has been set up with a European (UK) locale.

However, when I use the [Material Components Gallery](https://play.google.com/store/apps/details?id=com.numero.material_gallery) app (repo [here](https://github.com/NUmeroAndDev/MaterialGallery-android)) the manual input date is in the form `dd/MM/yyyy`... and they too are using the same material components version.

I can't figure out how to change it in my own code...

**Comment by kegan** [comment]
Anyone knows if this is fixed? Or is there a way to workaround?

**Comment by aljidy** [comment]
Try setting the locale to the default Locale whilst building the DatePicker with `Locale.setDefault()`

**Comment by Hmerman6006** [comment]
The user phone settings System > Date & time > Use location to set time zone influences the default format of MaterialDatePicker.
